[project]
name = 'Invox'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Invox]
path = 'contracts/Invox.clar'
clarity_version = 3
epoch = 3.1
[contracts.invoice-templates]
path = 'contracts/invoice-templates.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
